spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/music
    username: admin
    password: password

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: db/master.xml